
#!/bin/bash
#$ -cwd
#$ -o sublogs/A06b_check_contacts.$JOB_ID
#$ -j y
#$ -l h_rt=2:00:00,h_data=4G
#$ -N A06b_contactcheck
#$ -hold_jid A06a_quant_contacts



echo "Job $JOB_ID started on:   " `hostname -s`
echo "Job $JOB_ID started on:   " `date `
echo " "





# environment init -------------------------------------------------------------

export $(cat snm3C_parameters.env | grep -v '^#' | xargs) # <--



# extract target filepaths -----------------------------------------------------

query_metadat () {
  awk -F',' -v targetcol="$1" \
      'NR==1 {
                for (i=1;i<=NF;i++) {
                    if ($i==targetcol) {assayout=i; break} }
                print $assayout
              } 
      NR>1 {
                print $assayout
            }' $metadat_well
}

check_filepaths_in_assay() {
    for file in $@
        do 
        if [[ ! -s $file ]]
            then
                echo "missing '$file'"
            fi
        done
}

check_filepath_by_batch() {
target_array=($@)
batches_to_rerun=()
for ((target_batch=1; target_batch<=nbatches; target_batch++))
    do
        target_well_rows=()
        for ((row=1; row<=nwells; row++))
        do
            if [[ "${batchnum[$row]}" == "${target_batch}" ]]
            then
                target_well_rows+=($row)
            fi
        done

        batch_file_list=${target_array[@]: ${target_well_rows[0]}:${#target_well_rows[@]} }
    
        num_files_missing=$(check_filepaths_in_assay ${batch_file_list[@]} | wc -l)

        if [[ ${num_files_missing} > 0 ]]
        then
            batches_to_rerun+=(${target_batch})
            echo -e "${target_batch} \t ${num_files_missing}"
        fi
    done 
    
    if [[ ${#batches_to_rerun[@]} > 0 ]]
    then
        echo "batches to re-run:"
        echo "${batches_to_rerun[*]}"        
    fi
}

batchnum=($(query_metadat "batchnum"))

nwells=${#batchnum[@]}
nbatches=${batchnum[-1]}



# apply checks for A04a output -------------------------------------------------

echo "-----------------------------------------------------------------"
echo "A. printing number of final .pairs/metadat missing (by batch)... "
echo -e "-----------------------------------------------------------------\n\n"

file_pairs=($(query_metadat "A06a_pairs"))
file_meta3c=($(query_metadat "A06a_3c_metadat"))

echo "checking contact pairs:"
echo -e "batchnum\tnum_missing"
check_filepath_by_batch ${file_pairs[@]}

echo "checking pairs metadata:"
check_filepath_by_batch ${file_meta3c[@]}


echo -e "\n\nsuggest re-running and checking sublog output of above batches."



echo -e "\n\n-----------------------------------------------------------------"
echo "B. checking each expected .pairs/metadat file (from $metadat_well)"
echo -e "-----------------------------------------------------------------\n\n"

echo "* checks the A06a output columns of 'metadat_well' if the file exists and is non-empty."
echo "* if none missing, will only output target column names above."
echo "* if some declared 'missing' but all other checks OK, may just be no/few reads surviving trimming."
echo "  (check 'fastq_demultip/' and associated fastp logs e.g., fastq_trimmed/wellprefix.html report)"

echo -e "\nchecking contact pairs:\n"
check_filepaths_in_assay ${file_pairs[@]}

echo -e "\nchecking pairs metadata:\n"
check_filepaths_in_assay ${file_meta3c[@]}



echo -e "\n\n-----------------------------------------------------------------"
echo "C. checking log files for issues."
echo -e "-----------------------------------------------------------------\n"

echo "checking if 'completed' in sublogs/A06a_quant_contacts* output."
echo "if any filename is printed, the associated batch may have not completed allc gen."

grep -c 'ended on' sublogs/A06a_quant_contacts* | awk -F ":" '$2==0 {print $1}'





echo -e "\n\n'A06b_check_contacts' completed.\n\n"



echo "Job $JOB_ID ended on:   " `hostname -s`
echo "Job $JOB_ID ended on:   " `date `

